export const ADD_USER = 'AGREGAR_USUARIO';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const ADD_USER_SUCCESS  = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR  = 'ADD_USER_ERROR';


export const BEGIN_GET_USERS = 'COMENZAR_OBTENER_USUARIOS';
export const DOWNLOAD_USERS_SUCCESS = 'DESCARGA_USUARIOS_EXITO';
export const DOWNLOAD_USERS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const GET_USER_DELETE = 'OBTENER_USUARIO_ELIMINAR';
export const DELETE_USER_SUCCESS = 'USUARIO_ELIMINADO_EXITO';
export const DELETE_USER_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const GET_USER_EDIT = 'OBTENER_USUARIO_EDITAR';
export const BEGIN_EDIT_USER = 'COMENZAR_EDITAR_USUARIO';
export const USER_EDIT_SUCCESS = 'USUARIO_EDITADO_EXITO';
export const EDIT_USER_ERROR = 'USUARIO_EDITADO_ERROR';

/**Registro Usuario */
export const USER_REGISTER =  'REGISTRO_USUARIO';
export const USER_REGISTER_SUCCESS  =  'REGISTRO_USUARIO_EXITO';
export const USER_REGISTER_ERROR  =  'REGISTRO_USUARIO_ERROR';